name: Comment with mypy_primer diff

on:
  - pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  mypy_primer:
    name: Comment
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install adm-zip
      - name: Post comment
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Hello',
            })

      - uses: kanga333/comment-hider@v0.2.1
        name: Hide old comments
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          leave_visible: 1
