on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  foobar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo lol > foo
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3.8.2
        with:
          commit-message: Asdf
          title: Asdf2
