name: Remove unused stubtest whitelist entries

on:
  - pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  hello-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo hello > hello
      - name: Create pull request
        # v3.8.2
        uses: peter-evans/create-pull-request@052fc72b4198ba9fbc81b818c6e1859f747d49a8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Hello commit message
          title: "[gh-action] hello"
          base: master
